config/routes.rb
Rails.application.routes.draw do
    root "home#index"

    get "sign-up", to: "registrations#new"
    post "sign-up", to: "registrations#create"
    get "sign-in", to: "sessions#new"
    post "sign-in", to: "sessions#create"
    delete "sign-out", to: "sessions#destroy"

    # api based pages - view and save items
    get "/magic-items", to: "magic_items#index"
    get "magic-items/:slug", to: "magic_items#show"
    patch "/user/magic-items", to: "user#update_magic_items"

    get "/monsters", to: "monsters#index"
    get "/monsters/:slug", to: "monsters#show"
    patch "/user/monsters", to: "user#update_monsters"

    get "/spells", to: "spells#index"
    get "/spells/:slug", to: "spells#show"
    patch "/user/spells", to: "user#update_spells"

    # adventures
    get "campaigns/:campaign_slug/adventures/create", to: "adventures#new"
    post "campaigns/:campaign_slug/adventures/create", to: "adventures#create"
    get "campaigns/:campaign_slug/adventures/:adventure_slug", to: "adventures#show"
    put "campaigns/:campaign_slug/adventures/:adventure_slug", to: "adventures#update"

    # campaigns
    get "campaigns", to: "campaigns#index"
    get "campaigns/create", to: "campaigns#new"
    post "campaigns/create", to: "campaigns#create"
    get "campaigns/:campaign_slug", to: "campaigns#show"
    put "campaigns/:campaign_slug", to: "campaigns#update"

    # comments
    resources :campaigns do
        resources :comments, only: [:create]
    end
    resources :adventures do
        resources :comments, only: [:create]
    end
end

app/models/adventure.rb
class Adventure < ApplicationRecord
    belongs_to :campaign
    has_many :comments, as: :commentable, dependent: :destroy

    before_create :set_defaults

    validates :title, presence: true
    validates :slug, uniqueness: true

    def user_id
        campaign.user_id
    end

    private

    def set_defaults
        require 'securerandom'
        self.slug ||= SecureRandom.hex(4) # set only if doesn't exist
    end
end

app/models/api.rb
module Api
    module SavedItems
        def api_update_list(object, list, params)
            if params[:add_item]
                list << params[:add_item]
                object.save
            elsif params[:remove_item]
                list.delete params[:remove_item]
                object.save
            end
        end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
    belongs_to :user
    has_many :adventures
    has_many :comments, as: :commentable, dependent: :destroy
    
    before_create :set_defaults

    validates :title, presence: true
    validates :user_id, presence: true
    validates :slug, uniqueness: true

    private

    def set_defaults
        require 'securerandom'
        self.slug ||= SecureRandom.hex(5)
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :commentable, polymorphic: true # belongs to either Adventure or Campaign
    belongs_to :user

    validates :text, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/magic_item.rb
class MagicItem < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :campaigns, dependent: :destroy
    has_many :comments, dependent: :destroy

    validates :email, presence: true, uniqueness: true
    validates :username, presence: true, uniqueness: true
end

app/helpers/adventures_helper.rb
module AdventuresHelper
    def adventure_path campaign_slug, adventure_slug
        "#{campaigns_path}/#{campaign_slug}/adventures/#{adventure_slug}"
    end
end

app/helpers/api_helper.rb
module ApiHelper
    def save_magic_item_button slug
        return link_to "Log In", sign_in_path, class: "button button- button-small" if !Current.user

        if Current.user.saved_magic_items.include? slug
            return button_to "Remove Item", user_magic_items_path, method: :patch, class: "button button-dark button-small", params: { remove_item: slug }
        end

        button_to "Save Item", user_magic_items_path, method: :patch, class: "button button- button-small", params: { add_item: slug }
    end

    def save_spell_button slug
        return link_to "Log In", sign_in_path, class: "button button- button-small" if !Current.user

        if Current.user.saved_spells.include? slug
            return button_to "Remove Spell", user_spells_path, method: :patch, class: "button button-dark button-small", params: { remove_item: slug }
        end

        button_to "Save Spell", user_spells_path, method: :patch, class: "button button- button-small", params: { add_item: slug }
    end

    def save_monster_button slug
        return link_to "Log In", sign_in_path, class: "button button- button-small" if !Current.user

        if Current.user.saved_monsters.include? slug
            return button_to "Remove Monster", user_monsters_path, method: :patch, class: "button button-dark button-small", params: { remove_item: slug }
        end

        button_to "Save Monster", user_monsters_path, method: :patch, class: "button button- button-small", params: { add_item: slug }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
        return if text == nil || text == ''
        
        options = [:hard_wrap, :autolink, :no_intra_emphasis, :tables, :underline, :highlight, :quote, :footnotes]
        Markdown.new(text, *options).to_html.html_safe
    end

    def is_logged_in?
        !!Current.user
    end

    def to_url *array
        array.join('/')
    end

    def get_slug string
        string.split('/').last
    end

    def to_title string
        string.gsub('_', ' ').gsub('-', ' ').titleize
    end

    def is_owner? item
        # mostly for campaigns and adventures
        Current.user ? item.user_id.to_i == Current.user.id.to_i : false
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
    def campaign_path campaign_slug
        "#{campaigns_path}/#{campaign_slug}"
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/magic_items_helper.rb
module MagicItemsHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
    def hash_to_html_list hash, keys
        keys
            .select { |key| hash[key] != nil && hash[key] != '' }
            .map { |key| "<p>#{to_title key }: #{hash[key]}</p>" }.join.html_safe
    end

    def array_to_html_list array
        array.map { |key, value| "<p>#{to_title key }: #{value}</p>" }.join.html_safe
    end

    def array_to_html_links array
        array.map { |value| "<p><a href='#{value}'>#{value.split('/').last.titleize}</a></p>" }.join.html_safe
    end

    def get_ability_modifiers hash
        # sim to hash_to_html_list but adding modifiers
        keys = ['strength', 'dexterity', 'constitution', 'intelligence', 'wisdom', 'charisma']
        keys
            .map do |key|
                """<p>
                    #{to_title key}: #{hash[key]} 
                    (#{calculate_ability_modifier hash[key]})
                </p>"""
            end.join.html_safe
    end

    private

    def calculate_ability_modifier score
        # modifier score = ability score - 10 / 2
        (score - 10) / 2
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyD&amp;D</title>
    <link rel="icon" type="image/png" href="<%= image_path("dragon-logo.png", width: 48) %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/superkube@latest/dist/superkube.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    
    <div class="container centered">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_csv.html.erb
here

<%# TODO: quick solution only - move logic out of view %>

<%
rows = table.split("\n")
headings = rows[0].split(',')
data_rows = rows.drop(1)

%>

<table>
    <tr>
        <% for heading in headings %>
            <th><strong><%= heading %></strong></th>
        <% end %>
    </tr>
    <% for row in data_rows %>
        <tr>
            <% for column in row.split(',') %>
                <td><%= column %></td>
            <% end %>
        </tr>
    <% end %>
</table>

app/views/shared/_edit_plan.html.erb
<section class="modal-body shallow-stack-sm">
    <h2 class="heading-mega">
        Edit <%= type %>
    </h2>
    
    <%= form_with model: form_model, url: form_url, class: "container-content", local: true, method: :put do |form| %>        
        <div class="form-item">
            <%= form.label :title %>
            <%= form.text_field :title, class: "input" %>
        </div>
        <div class="form-item">
            <%= form.label :subtitle %>
            <%= form.text_field :subtitle, class: "input" %>
        </div>
        <div class="form-item">
            <%= form.label :description %>
            <%= form.text_area :description, class: "input", rows: 12 %>
        </div>

        <div class="form-item">
            <%= form.label :date_started %>
            <%= form.date_field :date_started, class: "input" %>
        </div>
        <% if type == "Campaign" %>
            <div class="form-item">
                <%= form.label :date_ended %>
                <%= form.date_field :date_ended, class: "input" %>
            </div>
        <% end %>

        <div class="form-item">
            <%= form.label :shared_notes %>
            <%= form.text_area :shared_notes, class: "input", rows: 12 %>
        </div>
        <div class="form-item">
            <%= form.label :private_notes %>
            <%= form.text_area :private_notes, class: "input", rows: 12 %>
        </div>

        <div class="form-item">
            <%= form.label :public %>
            <%= form.check_box :public, class: "input" %>
        </div>
        <div class="form-item">
            <%= form.label :archived %>
            <%= form.check_box :archived, class: "input" %>
        </div>

        <%= form.submit "Save", data: {turbo: false}, class: "button button-primary" %>
        <button
            onclick="document.getElementById('edit-modal').classList.add('hidden')"
            data-type="close"
            class="button"
            >Close</button>
    <% end %>
</section>

app/views/shared/_navbar.html.erb
<div class="navbar container centered">
    <div class="navbar-container">
        <div class="navbar-brand">
            <a href="<%= root_path %>" class="brand">
                <%= image_tag("dragon-logo.png", width: 48) %>
            </a>
        </div>
        <div class="navbar-nav flex-auto">
            <nav class="nav nav-centered">
                <ul class="nav-list">
                    <li class="nav-item">
                        <%= link_to "Home", root_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Campaigns", campaigns_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Magic Items", magic_items_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Spells", spells_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Monsters", monsters_path, class: "nav-link" %>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="navbar-action">
            <% if is_logged_in? %>
                <%= button_to "Sign Out", sign_out_path, method: :delete, class: "button button-secondary button-small" %>
            <% else %>
                <%= link_to "Log In", sign_in_path, class: "button button-secondary button-small mr-2" %>
                <%= link_to "Sign Up", sign_up_path, class: "button button-primary button-small" %>
            <% end %>
        </div>
    </div>
</div>