config/routes.rb
Rails.application.routes.draw do
    root "home#index"

    get "sign-up", to: "registrations#new"
    post "sign-up", to: "registrations#create"
    get "sign-in", to: "sessions#new"
    post "sign-in", to: "sessions#create"
    delete "sign-out", to: "sessions#destroy"

    # api based pages - view and save items
    get "/magic-items", to: "magic_items#index"
    get "magic-items/:slug", to: "magic_items#show"
    patch "/user/magic-items", to: "user#update_magic_items"

    get "/monsters", to: "monsters#index"
    get "/monsters/:slug", to: "monsters#show"
    patch "/user/monsters", to: "user#update_monsters"

    get "/spells", to: "spells#index"
    get "/spells/:slug", to: "spells#show"
    patch "/user/spells", to: "user#update_spells"

    # adventures
    get "campaigns/:campaign_slug/adventures/create", to: "adventures#new"
    post "campaigns/:campaign_slug/adventures/create", to: "adventures#create"
    get "campaigns/:campaign_slug/adventures/:adventure_slug", to: "adventures#show"
    put "campaigns/:campaign_slug/adventures/:adventure_slug", to: "adventures#update"

    # campaigns
    get "campaigns", to: "campaigns#index"
    get "campaigns/create", to: "campaigns#new"
    post "campaigns/create", to: "campaigns#create"
    get "campaigns/:campaign_slug", to: "campaigns#show"
    put "campaigns/:campaign_slug", to: "campaigns#update"

    # comments
    resources :campaigns do
        resources :comments, only: [:create]
    end
    resources :adventures do
        resources :comments, only: [:create]
    end
end

app/models/adventure.rb
class Adventure < ApplicationRecord
    belongs_to :campaign
    has_many :comments, as: :commentable, dependent: :destroy

    before_create :set_defaults

    validates :title, presence: true
    validates :slug, uniqueness: true

    def user_id
        campaign.user_id
    end

    private

    def set_defaults
        require 'securerandom'
        self.slug ||= SecureRandom.hex(4) # set only if doesn't exist
    end
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController    
    def show
        @campaign = get_campaign(false)
        @adventure = Adventure.find_by(:slug => params['adventure_slug'])
        @comments = @adventure.comments.order(:created_at)
    end
    
    def new
        @campaign = get_campaign
        @adventure = Adventure.new
    end
    
    def create
        @campaign = get_campaign
        return nil if @campaign == nil

        @adventure = @campaign.adventures.build allowed_params
        if @adventure.save
            redirect_to "/campaigns/#{@campaign['slug']}/adventures/#{@adventure['slug']}", notice: "New Adventure Created"
        else
            render :new
        end
    end

    def update
        campaign = get_campaign
        return nil if !campaign

        adventure = Adventure.find_by(:slug => params['adventure_slug'])
        adventure.attributes = allowed_params
        if adventure.save
            redirect_to "#{campaigns_path}/#{params['campaign_slug']}/adventures/#{params['adventure_slug']}", notice: "Campaign Updated"
        else
          redirect_to "#{campaigns_path}/#{params['campaign_slug']}/adventures/#{params['adventure_slug']}", notice: "Failed to Save"
        end
    end
    
    private

    def is_owner? item
        Current.user ? item.user_id.to_i == Current.user.id.to_i : false
    end

    def has_permission? campaign, adventure, must_be_owner=true
        is_owner = is_owner? campaign
        is_owner || (adventure&.public && must_be_owner == false)
    end

    def get_campaign(must_be_owner=true)
        campaign = Campaign.find_by(:slug => params['campaign_slug'])
        adventure = Adventure.find_by(:slug => params['adventure_slug'])
        
        if campaign && has_permission?(campaign, adventure, must_be_owner)
            return campaign
        elsif adventure
            render html: 'Adventure is not public'
            return nil
        else
            render html: '404: Adventure Not Found'
            return nil
        end
    end
    
    def allowed_params
        params.require(:adventure)
          .permit(
            :title,
            :subtitle,
            :description,
            :public,
            :archived,
            :shared_notes,
            :private_notes,
            :date_started,
            :date_ended,
          )
    end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
    def adventure_path campaign_slug, adventure_slug
        "#{campaigns_path}/#{campaign_slug}/adventures/#{adventure_slug}"
    end
end

app/views/adventures/new.html.erb
<div class="container mt-8 shallow-stack-sm">
    <h1 class="heading-mega">Create New Adventure</h1>
    <h2>Create a new adventure for <%= @campaign['title'] %></h2>

    <%= form_with model: @adventure, url: "/campaigns/#{@campaign['slug']}/adventures/create", class: "form container-small", local: true do |form| %>
        <% if @adventure.errors.any? %>
            <div class="alert alert-error my-2">
                <% @adventure.errors.full_messages.each do |message| %>
                    <div><%= message %></div>
                <% end %>
            </div>
        <% end %>

        <div class="form-item">
            <%= form.label :title %>
            <%= form.text_field :title, class: "input", placeholder: "Our Adventure" %>
        </div>

        <%= form.submit "Create", data: {turbo: false}, class: "button button-primary" %>
    <% end %>
</div>

app/views/adventures/show.html.erb
<div class="container mt-8">
    <div class="grid">
        <div class="column column-6 stack-sm">
            <h1 class="heading-mega"><%= @adventure['title'] %></h1>
            <p><a href="<%= campaign_path @campaign['slug'] %>">Go to Campaign (<%=@campaign['title']%>)</a></p>
            <h2 class="heading-medium"><%= @adventure['subtitle'] %></h2>
            <p>Dates: <%= @adventure['date_started'] %></p>

            <div class="card">
                <h3 class="h6">Description</h3>
                <div class="stack-xs markdown"><%= markdown @adventure['description'] %></div>
            </div>

            <h2 class="heading-medium">Shared Notes</h2>
            <div class="stack-xs markdown"><%= markdown @adventure['shared_notes'] %></div>

            <% if is_owner?(@adventure) %>
                <h2 class="heading-medium">Private Notes</h2>
                <div class="stack-xs markdown"><%= markdown @adventure['private_notes'] %></div>
            <% end %>
        </div>
    </div>


    <% if is_owner? @campaign %>        
        <div class="container mt-4 mb-8 shallow-stack-sm">
            <div id="edit-modal" class="modal hidden">
                <div class="modal-box">
                    <%= render partial: "shared/edit_plan", locals: { form_model: @adventure, form_url: adventure_path(@campaign['slug'], @adventure['slug']), type: 'Adventure' } %>
                </div>
            </div>

            <button
                onclick="document.getElementById('edit-modal').classList.remove('hidden')"
                class="button button-primary button-small"
                >Edit Adventure</button>
        </div>
    <% end %>


    <div class="container-content mt-4 mb-8 shallow-stack-sm">
        <h2 class="heading-medium">Comments</h2>
        <% for comment in @comments %>
            <div class="card p-4 pb-7 border-dark-mid border-top">
                <strong><%= comment.user.username %></strong>
                <p class="mb-0"><small style="font-size: 12px; color: #777; padding-top: 0;"><%= comment.created_at.to_formatted_s(:short) %> UTC</small></p>
                <div class="stack-xs markdown">
                    <% if comment.is_csv %>
                        <%= render partial: "shared/csv", locals: { table: comment.text } %>
                    <% else %>
                        <%= markdown comment.text %>
                    <% end %>
                </div>
            </div>
        <% end %>
        <% if @comments.empty? %>No comments<% end %>

        <% if is_logged_in? %>
            <%= form_with(model: [@adventure, Comment.new], class: "form", local: true) do |form| %>
                <div class="form-item">
                    <%= form.label :text, "Add comment (markdown supported)" %>
                    <%= form.text_area :text, placeholder: "Add a comment...", class: "input" %>
                </div>
                <div class="form-item">
                    <%= form.label :is_csv, "Display as table (must be in CSV format)" %>
                    <%= form.check_box :is_csv, class: "input", rows: 3 %>
                </div>
                <%= form.hidden_field :adventure_id, value: @adventure.id %>
                <%= form.submit "Add Comment", class: "button button-primary button-small" %>
            <% end %>
        <% end %>
    </div>
</div>