config/routes.rb
Rails.application.routes.draw do
    root "home#index"

    get "sign-up", to: "registrations#new"
    post "sign-up", to: "registrations#create"
    get "sign-in", to: "sessions#new"
    post "sign-in", to: "sessions#create"
    delete "sign-out", to: "sessions#destroy"

    # api based pages - view and save items
    get "/magic-items", to: "magic_items#index"
    get "magic-items/:slug", to: "magic_items#show"
    patch "/user/magic-items", to: "user#update_magic_items"

    get "/monsters", to: "monsters#index"
    get "/monsters/:slug", to: "monsters#show"
    patch "/user/monsters", to: "user#update_monsters"

    get "/spells", to: "spells#index"
    get "/spells/:slug", to: "spells#show"
    patch "/user/spells", to: "user#update_spells"

    # adventures
    get "campaigns/:campaign_slug/adventures/create", to: "adventures#new"
    post "campaigns/:campaign_slug/adventures/create", to: "adventures#create"
    get "campaigns/:campaign_slug/adventures/:adventure_slug", to: "adventures#show"
    put "campaigns/:campaign_slug/adventures/:adventure_slug", to: "adventures#update"

    # campaigns
    get "campaigns", to: "campaigns#index"
    get "campaigns/create", to: "campaigns#new"
    post "campaigns/create", to: "campaigns#create"
    get "campaigns/:campaign_slug", to: "campaigns#show"
    put "campaigns/:campaign_slug", to: "campaigns#update"

    # comments
    resources :campaigns do
        resources :comments, only: [:create]
    end
    resources :adventures do
        resources :comments, only: [:create]
    end
end

app/models/campaign.rb
class Campaign < ApplicationRecord
    belongs_to :user
    has_many :adventures
    has_many :comments, as: :commentable, dependent: :destroy
    
    before_create :set_defaults

    validates :title, presence: true
    validates :user_id, presence: true
    validates :slug, uniqueness: true

    private

    def set_defaults
        require 'securerandom'
        self.slug ||= SecureRandom.hex(5)
    end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
    def index
        return @campaigns = [] if !Current.user
        @campaigns = Current.user.campaigns.order(updated_at: :desc)
    end

    def show
        @campaign = get_campaign(false)
        if @campaign
            @adventures = get_adventures @campaign
            @comments = @campaign.comments.order(:created_at)    
        end
    end

    def new
        @campaign = Campaign.new
    end

    def create
        @campaign = Current.user.campaigns.create allowed_params
        if @campaign.save
            redirect_to "#{campaigns_path}/#{@campaign.slug}", notice: "New Campaign Created"
        else
            render :new
        end
    end

    def update
        @campaign = get_campaign 
        return nil if @campaign == nil

        @campaign.attributes = allowed_params
        if @campaign.save
            redirect_to "#{campaigns_path}/#{@campaign.slug}", notice: "Campaign Updated"
        else
            redirect_to "#{campaigns_path}/#{@campaign.slug}", notice: "Failed to Save"
        end
    end

    private

    def is_owner? item
        Current.user ? Current.user.id.to_i == item.user_id.to_i : false
    end

    def has_permission? item, must_be_owner=true
        is_owner = is_owner? item
        is_owner || (item&.public && must_be_owner == false)
    end

    def get_adventures campaign
        adventures = campaign.adventures.order(date_started: :desc)
        adventures.select { |adventure| has_permission? adventure, false }
    end

    def get_campaign(must_be_owner=true)
        campaign = Campaign.find_by(:slug => params['campaign_slug'])
        if campaign && has_permission?(campaign, must_be_owner)
            return campaign
        elsif campaign
            render html: 'Campaign is not public'
            return nil
        else
            render html: '404: Campaign Not Found'
            return nil
        end
    end

    def allowed_params
        params.require(:campaign)
            .permit(
                :title,
                :subtitle,
                :description,
                :public,
                :archived,
                :shared_notes,
                :private_notes,
                :date_started,
                :date_ended,
            )
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
    def campaign_path campaign_slug
        "#{campaigns_path}/#{campaign_slug}"
    end
end

app/views/campaigns/index.html.erb
<div class="container mt-8 stack-sm">
    <h1 class="heading-mega">My Campaigns</h1>

    <% for campaign in @campaigns %>
        <div class="mb-4">
            <a href="<%= campaign_path campaign.slug %>">
                <strong><%= campaign.title %></strong>
            </a>
        </div>
    <% end %>

    <% if is_logged_in? %>
        <%= link_to "Add Campaign", campaigns_create_path, class: "button button-primary"  %>
    <% else %>
        <%= link_to "Log in", sign_in_path %> or <%= link_to "sign up", sign_up_path %> to create campaigns.
    <% end %>
</div>

app/views/campaigns/new.html.erb
<div class="container mt-8 shallow-stack-sm">
    <h1 class="heading-mega">Create New Campaign</h1>

    <div class="container-small">
        <%= form_with model: @campaign, url: campaigns_create_path, class: "form", local: true do |form| %>
            <% if @campaign.errors.any? %>
                <div class="alert alert-error my-2">
                    <% @campaign.errors.full_messages.each do |message| %>
                        <div><%= message %></div>
                    <% end %>
                </div>
            <% end %>

            <div class="form-item">
                <%= form.label :title %>
                <%= form.text_field :title, class: "input", placeholder: "My Campaign" %>
            </div>
            
            <%= form.submit "Create", data: {turbo: false}, class: "button button-primary" %>
        <% end %>
    </div>
</div>

app/views/campaigns/show.html.erb
<div class="container mt-8">
    <div class="grid stack-sm">
        <div class="column column-6 stack-sm">
            <h1 class="heading-mega"><%= @campaign['title'] %></h1>
            <h2 class="heading-medium"><%= @campaign['subtitle'] %></h2>
            <p>Dates: <%= @campaign['date_started'] %> - <%= @campaign['date_ended'] %></p>

            <h2 class="heading-medium">Description</h2>
            <div class="stack-xs markdown"><%= markdown @campaign['description'] %></div>

            <h2 class="heading-medium">Shared Notes</h2>
            <div class="stack-xs markdown"><%= markdown @campaign['shared_notes'] %></div>

            <% if is_owner?(@campaign) %>
                <h2 class="heading-medium">Private Notes</h2>
                <div class="stack-xs markdown"><%= markdown @campaign['private_notes'] %></div>
            <% end %>
        </div>


        <div class="column column-6">
            <h2 class="heading-medium">Adventures</h2>
            <% for adventure in @adventures %>
                <div class="my-2">
                    <a href="<%= adventure_path @campaign['slug'], adventure['slug'] %>">
                        <%= adventure['title'] %>
                        <% if adventure['date_started'] %>(<%= adventure['date_started'] %>)<% end %>
                    </a>
                </div>
            <% end %>
            <% if is_owner? @campaign %>
                <%= link_to "New Adventure", "/campaigns/#{@campaign["slug"]}/adventures/create", class: "button button-primary button-small mt-2" %>
            <% end %>
        </div>
    </div>


    <% if is_owner? @campaign %>        
        <div class="container mt-4 mb-8 shallow-stack-sm">
            <div id="edit-modal" class="modal hidden">
                <div class="modal-box">
                    <%= render partial: "shared/edit_plan", locals: { form_model: @campaign, form_url: campaign_path(@campaign['slug']), type: 'Campaign' } %>
                </div>
            </div>

            <button
                onclick="document.getElementById('edit-modal').classList.remove('hidden')"
                class="button button-primary button-small"
                >Edit Campaign</button>
        </div>
    <% end %>


    <div class="container-content mt-4 mb-8 shallow-stack-sm">
        <h2 class="heading-medium">Comments</h2>
        <% for comment in @comments %>
            <div class="card p-4 pb-7 border-dark-mid border-top">
                <strong><%= comment.user.username %></strong>
                <p class="mb-0"><small style="font-size: 12px; color: #777; padding-top: 0;"><%= comment.created_at.to_formatted_s(:short) %> UTC</small></p>
                <div class="stack-xs markdown">
                    <% if comment.is_csv %>
                        <%= render partial: "shared/csv", locals: { table: comment.text } %>
                    <% else %>
                        <%= markdown comment.text %>
                    <% end %>
                </div>
            </div>
        <% end %>
        <% if @comments.empty? %>No comments<% end %>

        <% if is_logged_in? %>
            <%= form_with(model: [@campaign, Comment.new], class: "form", local: true) do |form| %>
                <div class="form-item">
                    <%= form.label :text, "Add comment (markdown supported)" %>
                    <%= form.text_area :text, placeholder: "Add a comment...", class: "input", rows: 3 %>
                </div>
                <div class="form-item">
                    <%= form.label :is_csv, "Display as table (must be in CSV format)" %>
                    <%= form.check_box :is_csv, class: "input", rows: 3 %>
                </div>
                <%= form.hidden_field :campaign_id, value: @campaign.id %>
                <%= form.submit "Add Comment", class: "button button-primary button-small" %>
            <% end %>
        <% end %>
    </div>
</div>